# Generated by Django 6.0.1 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appusagestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUsageStats',
        ),
        migrations.AlterField(
            model_name='servicevendor',
            name='category',
            field=models.CharField(choices=[('medical', 'MEDICAL'), ('grocery', 'GROCERY'), ('transport', 'TRANSPORT'), ('home care', 'HOMECARE')], max_length=20),
        ),
    ]
