# Generated by Django 6.0.1 on 2026-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_appusagestats_alter_servicevendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('music', 'Music'), ('spiritual', 'Spiritual'), ('social', 'Social')], max_length=20),
        ),
    ]
