# Generated by Django 5.2.11 on 2026-02-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevendor',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('GROCERY', 'Grocery'), ('TRANSPORT', 'Transport'), ('HOME CARE', 'Home Care'), ('PHYSIOTHERAPY', 'Physiotherapy')], max_length=20),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('PHONE_CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for completed calls)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about the call')),
                ('emergency_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='base.emergencycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='base.servicevendor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
