# Generated by Django 5.2.11 on 2026-02-28 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_servicevendor_category_calllog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('music', 'Music'), ('spiritual', 'Spiritual'), ('social', 'Social')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_live', 'start_time'], name='base_event_is_live_f4d39c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_time'], name='base_event_categor_f011d2_idx'),
        ),
    ]
