# Generated by Django 5.2.11 on 2026-02-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_options_alter_event_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed to Send'), ('PENDING', 'Pending')], default='SENT', max_length=20)),
                ('message', models.TextField(default='SOS! Emergency help needed.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='base.emergencycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
